platform :ios, '8.0'

target 'OneToOneCallSample' do
  node_modules_path = '../node_modules'

  pod 'yoga', path: "#{node_modules_path}/react-native/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: "#{node_modules_path}/react-native", :subspecs => ['DevSupport', 'RCTNetwork']

  pod 'RNStringee', path: "#{node_modules_path}/stringee-react-native/ios"
  
  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

end




